deploy:
  runs-on: ubuntu-latest
  needs: Build With Jib

  steps:
    - name: Get verion
      id: image
      run: |
        VERSION=$(echo ${{ github.sha }} | cut -c1-8)
        echo VERSION=$VERSION
        echo "::set-output name=version::$VERSION"

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1

    - name: Checkout kustomize repository
      uses: actions/checkout@v2
      with:
        repository: ${{ secrets.DOCKER_REPOSITORY }}/${{ secrets.DOCKER_IMAGE }}
        ref: dev
        token: ${{ secrets.ACTION_TOKEN }}
        path: canal-k8s-manifests

    - name: Update Kubernetes resources
      run: |
        cd canal-k8s-manifests/overlays/dev/
        kustomize edit set image ${{ secrets.DOCKER_IMAGE }}:${{ steps.image.outputs.version }}
        cat kustomization.yaml

    - name: Commit files
      run: |
        cd canal-k8s-manifests
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        git commit -am "Update image tag"
        git push -u origin master